### ISSUE TITLE
category view problem

### ISSUE THREAD

**Issue by limatola** [coorasse/Airesis#101]
I have this problem that I can not understand. Is the same problem for all categories ( proposals , groups and blogs).

I can successfully create proposals groups and blogs, but they only appear correctly in the home.
I can not view them in their respective categories.

Here I can see properly: http://oi59.tinypic.com/30vbzbd.jpg

But here I can not see properly:

Proposals: http://oi58.tinypic.com/sg4ysi.jpg

Groups: http://oi61.tinypic.com/5ba5g8.jpg

Blogs: http://oi60.tinypic.com/2hf0y86.jpg

**Comment by coorasse** [comment]
Hi. SOLR is probably not indexing correctly your data. double check if is correctly indexing content and let me know

**Comment by limatola** [comment]
My system is Ubuntu 14.04, i have installed java oracle 8 and i use the command `rake sunspot:solr:start` and SOLR give me `Successfully started Solr ...`.

This is a screenshot: http://oi62.tinypic.com/1pysz7.jpg

This is sunspot-solr-development.log: 
http://pastebin.com/pnKzDxxB 
http://pastebin.com/x7bVhDB8

What i have to do?

**Comment by coorasse** [comment]
Can you try running `rake sunspot:solr:reindex` and then reloading the groups page? If the groups appear then you have an indexing problem, if they do not then the problem may be somewhere else.

You can also try disabling sidekiq for solr, commenting everything on config/initializers/sunspot.rb and reindexing again.

**Comment by limatola** [comment]
I solved with your command `rake sunspot:solr:reindex`. 

if it does not index , just turn off sidekiq , enter the command and then reactivate sidekiq
