### ISSUE TITLE
Locked users & ACTIVE_USERS_PERCENTAGE 

### ISSUE THREAD

**Issue by limatola** [coorasse/Airesis#105]
Blocked users are counted anyway in the variable ACTIVE_USERS_PERCENTAGE.

We need a patch to fix this problem. :-)

**Comment by coorasse** [comment]
The problem is here:
https://github.com/coorasse/Airesis/blob/master/app/models/user.rb#L141

It counts all users. Should exclude inactive ones. PR welcome! ;)

**Comment by limatola** [comment]
You could add a subtraction. A subtraction of the blocked users number?

**Comment by limatola** [comment]
problem solved with Airesis v. 4.2.4
