### ISSUE TITLE
Solr configuration removed

### ISSUE THREAD

**Issue by mion00** [coorasse/Airesis#132]
In 7480dce9957c5ea5ffa647d9f26ae73d51a1150f you removed all files related to solr. This however leaves us without a configuration for development and testing environments, leading to test failures.
Is there a reason why you removed the config files?

**Comment by coorasse** [comment]
since the solr configuration is personal and can contain sensible information only the example is provided (like for database.yml or application.yml). However this shouldn't bring problems during tests.

**Comment by mion00** [comment]
For istance here
<https://travis-ci.org/mion00/Airesis/builds/101893979#L7401> I see that in
the test is trying to connect to solr server (running in a docker
container), but it fails.
While debugging locally this issue, I found out that the solr server cannot
start its cores:[image: Inline images 1]
I think it is an issue with the configuration of it. What are the bare
minimum files required for running solr?
I am using solr/solr.xml and solr/config/solrconfig.xml.
Am I missing something?

**Comment by mion00** [comment]
My bad! I put the dockerfile to build the solr container in the solr directory, but doing so made sunspot think that solr was already configured, not triggering the creation of all the required files at servers startup! :expressionless:
