### ISSUE TITLE
How to change Amazon S3 with local upload

### ISSUE THREAD

**Issue by leandresca** [coorasse/Airesis#96]
How I can easily change Amazon S3 , with local upload?

Can you please describe the steps to follow?

Thanks for help.

**Comment by leandresca** [comment]
Stop! I just realized the big advantages of Amazon S3 compared to storing it locally.

The S3 price is very low , and allows me to be lighter on the VPN .

I close this topic!!!

**Comment by coorasse** [comment]
I think Airesis should easily allow to not use AmazonS3, even if it is convenient.
