### ISSUE TITLE
S3 backend problem

### ISSUE THREAD

**Issue by leandresca** [coorasse/Airesis#97]
This is my problem: http://oi60.tinypic.com/2nst85l.jpg

If i load avatars works well , but I have this problem in the group documents. I use airesis 4.0.14.

What am I doing wrong?

I have set up AWS_BUCKET: "" AWS_ACCESS_KEY_ID: "" AWS_SECRET_ACCESS_KEY: "".

**Comment by coorasse** [comment]
Group documents are not yet connected to amazonS3. I guess you are missing a folder in airesis  project: `private/elfinder`.

**Comment by leandresca** [comment]
Yeah!! Now works!  my fault , I used the command `rake db:setup`, and I did not give the command `mkdir -p private/elfinder`.

missing in the README.md
