### ISSUE TITLE
Feedback, ERROR_SENDER and ERROR_RECEIVER

### ISSUE THREAD

**Issue by leandresca** [coorasse/Airesis#98]
1. What is the difference between `ERROR_SENDER` and `ERROR_RECEIVER` in the `application.yml`? 
(I did not really understand how they work.)

2. I have a problem with feedback. Assuming that if I try to register a new user, the confirmation email arrives properly in inbox. 
When I send feedback , even if the message is sent correctly, do not receive it in the inbox. Why?

This is my application.yml: http://oi58.tinypic.com/nd64vl.jpg
Feedback: http://oi59.tinypic.com/9k9u28.jpg
Feedback terminal: http://oi60.tinypic.com/fxdueo.jpg

Airesis version = 4.0.14,   `sidekiq` started

Thanks so much for help.

**Comment by coorasse** [comment]
1. I don;t think you need them. were email addreses for sender and receiver of exceptions via email

2. Did you activate sidekiq?

**Comment by leandresca** [comment]
1. Ok, I do not need

2. Yes, I sidekiq active in a second terminal with the command `sidekiq` look this screenshot: http://oi58.tinypic.com/jkd0zl.jpg

But in what mailbox should reach the feedback sent?
(I thought the ratings were related to variables Error Sender or Error Reciver)

**Comment by coorasse** [comment]
Latest release 4.0.16 should allow you to configure emails for feedback
